tfg/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('', include('tfgcore.urls')),
    path('admin/', admin.site.urls),
]

tfgcore/urls.py
from django.urls import path
from . import views

app_name = 'tfgcore'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('about', views.about, name='about'),
    path('personaldata', views.personaldata, name='personaldata'),
    path('question01', views.question01, name='question01'),
    path('question02', views.question02, name='question02'),
    path('question03', views.question03, name='question03'),
    path('question04', views.question04, name='question04'),
    path('question05', views.question05, name='question05'),
    path('question06', views.question06, name='question06'),
    path('question07', views.question07, name='question07'),
    path('question08', views.question08, name='question08'),
    path('question09', views.question09, name='question09'),
    path('bye', views.bye, name='bye'),
    path('legalstuff', views.legalstuff, name='legalstuff'),
    path('testformwidgets', views.testformwidgets, name='testformwidgets'),
]

templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>
    <head>
            <meta charset="utf-8">
            <meta content="width=device-width, initial-scale=1" name="viewport">
            <title>
                {% block title %}
                    {% if title %}
                        {{title}}
                    {% else %}
                        Encuesta
                    {% endif %}
                {% endblock %}
            </title>
            <link href="{% static 'tfgcore/css/fontawesome/css/all.css' %}" rel="stylesheet">
            <link href="{% static 'tfgcore/css/bulma/css/bulma.min.css' %}" rel="stylesheet">
            <link href="{% static 'tfgcore/css/bulma/css/bulma-slider.min.css' %}" rel="stylesheet">
            <link href="{% static 'tfgcore/css/bulma/css/bulma-checkradio.min.css' %}" rel="stylesheet">
    </head>
    <body>
        {% block progress %}
        {% endblock %}
        {% block body %}
        {% endblock %}
        {% block footer %}
        <footer class="footer">
            <nav class="navbar">
                <div class="navbar-menu">
                    <div class="navbar-end">
                        <a class="navbar-item" href="{% url 'tfgcore:landing' %}">
                            Inicio
                        </a>
                        <a class="navbar-item" href="{% url 'tfgcore:legalstuff' %}">
                            Aviso Legal
                        </a>
                        <a class="navbar-item" href="{% url 'tfgcore:about' %}">
                            Sobre la Encuesta
                        </a>
                    </div>
                </div>
            </nav>
        </footer>
        {% endblock %}
        {% block modal %}
            {% block modalcontent %}
        
            {% endblock %}
        {% endblock %}
  
        {% block js %}
            <script src="{% static 'tfgcore/js/bulma-slider.min.js' %}"></script>
            <script>
                bulmaSlider.attach();
            </script>
        {% endblock %}
    </body>
</html>

templates/baseform.html
{% extends "base.html" %}
{% load static %}
{% block modal %}
<div class="modal" id="infodlg">
    <div class="modal-background"></div>
    <div class="modal-content">
        <div class="box">
            <h2 class="is-size-3 has-text-weight-bold">Sabías que...</h2>
            <div class="columns">
                <div class="column is-one-third">
                    <figure class="image">
                        <img src="{% static 'tfgcore/img/usr_avtr.svg' %}">
                    </figure>
                </div>
                <div class="column">
                    {% block modalcontent %}
                    {% endblock%}
            </div>
        </div>
      </div>
    
      <a href class="modal-close is-large" aria-label="close"></a>
</div>
{% endblock %}

{% block js %}
{{block.super}}
<script>
function showModal(){
    infodlg = document.getElementById("infodlg");
    infodlg.classList.add("is-active")
}
</script>
{% endblock %}