tfg/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('', include('tfgcore.urls')),
    path('admin/', admin.site.urls),
]

tfgcore/urls.py
from django.urls import path
from . import views

app_name = 'tfgcore'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('about', views.about, name='about'),
    path('personaldata', views.personaldata, name='personaldata'),
    path('question01', views.question01, name='question01'),
    path('question02', views.question02, name='question02'),
    path('question03', views.question03, name='question03'),
    path('question04', views.question04, name='question04'),
    path('question05', views.question05, name='question05'),
    path('question06', views.question06, name='question06'),
    path('question07', views.question07, name='question07'),
    path('question08', views.question08, name='question08'),
    path('question09', views.question09, name='question09'),
    path('bye', views.bye, name='bye'),
    path('legalstuff', views.legalstuff, name='legalstuff'),
    path('testformwidgets', views.testformwidgets, name='testformwidgets'),
]

tfgcore/views.py
import hashlib
from django.shortcuts import render, redirect
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.utils.datastructures import MultiValueDictKeyError
from django.urls import reverse
from .models import Participant, Answers

def landing(request):
    return render(request, 'tfgcore/landing.html')


def about(request):
    return render(request, 'tfgcore/sobre_la_encuesta.html')


def personaldata(request):
    def validate(p):
        msgs = []
        try:
            if len(p["email"]) == 0:
                msgs.append("Tienes que especificar un correo electrónico.")
            else:
                try:
                    validate_email(p["email"])
                except ValidationError:
                    msgs.append("El correo electrónico no parece ser válido.")
        except KeyError:
            msgs.append("Tienes que especificar un correo electrónico.")
        if int(p["agerange"]) == 0:
            msgs.append("Tienes que especificar un rango de edad.")
        if p["gender"] == "":
            msgs.append("Tienes que especificar tu género.")
        return msgs
    
    def populate(p):
        formdata = {
            "agerange": p.get('agerange'),
            "gender": p.get('gender'),
            "email": p.get('email'),
            "education": p.get('education')
        }
        return formdata

    if request.method == "POST":
        msgs = validate(request.POST)
        m = hashlib.sha256()
        m.update(request.POST["email"].encode())
        username = m.hexdigest()
        if User.objects.filter(username = username).exists():
            msgs.append('parece que ya has participado en la encuesta. Solo se puede participar una vez.')
        if len(msgs)>0:
            formdata = populate(request.POST)
            return render(request, 'tfgcore/personaldata.html', {"msgs":msgs, "formdata": formdata})
        email = "{0}@markusbarth.net".format(username)
        password = "unsecureP@sswrd"
        User.objects.create_user(username, email, password)
        usr = authenticate(username=username, password=password)
        login(request, usr)
        agerange = int(request.POST["agerange"])
        gender = request.POST["gender"]
        health_care_professional = False
        if request.POST["healthprofessional"] == "Yes":
            health_care_professional = True
        smoking = False
        if request.POST["smoker"] == "Yes":
            smoking = True
        sports = False
        if request.POST["sport"] == "Yes":
            sports = True
        chronic_disease = False
        if request.POST["pathologies"] == "Yes":
            chronic_disease = True
        

        participant = Participant(
            user=usr, 
            age_range=agerange, 
            gender=gender, 
            health_care_professional=health_care_professional,
            smoking=smoking,
            sports=sports,
            chronic_disease=chronic_disease
            )
        participant.save()
        
        return redirect(reverse('tfgcore:question01'))
    return render(request, 'tfgcore/personaldata.html')


@login_required
def question01(request):
    if request.method == "POST":
        msgs = []
        try:
            intreatment = request.POST["intreatment"]
        except MultiValueDictKeyError:
            msgs.append("Por favor, marca una de las respuestas.")
            return render(request, 'tfgcore/question01.html', {"msgs": msgs})
        answers = Answers(user=request.user, answer01=int(intreatment))
        answers.save()
        if intreatment in ['2', '3']:
            return redirect(reverse('tfgcore:question02'))
        else: 
            return redirect(reverse('tfgcore:question03'))
    return render(request, 'tfgcore/question01.html')


@login_required
def question02(request):
    if request.method == "POST":
        msgs = []
        if request.POST.get('treatmenttype') is None and len(request.POST['othertreatment'])==0:
            msgs.append("Por favor, marca al menos una de las casillas o describe el tipo del tratamiento recibido en el cuadro de texto de abajo.")
            return render(request, 'tfgcore/question02.html', {"msgs":msgs})
        answers = Answers.objects.filter(user=request.user)[0]
        treatmenttype = request.POST.getlist('treatmenttype')
        if '1' in treatmenttype:
            answers.answer01a = True
        if '2' in treatmenttype:
            answers.answer01b = True
        if '3' in treatmenttype:
            answers.answer01c = True
        if '4' in treatmenttype:
            answers.answer01d = True
        if '5' in treatmenttype:
            answers.answer01e = True
        if '6' in treatmenttype:
            answers.answer01f = True
        if '7' in treatmenttype:
            answers.answer01g = True
        if '8' in treatmenttype:
            answers.answer01h = True
        if len(request.POST['othertreatment'])>0:
            answers.answer01i = request.POST['othertreatment']
        answers.save()

        return redirect(reverse('tfgcore:question03'))
    return render(request, 'tfgcore/question02.html')


@login_required
def question03(request):
    if request.method == "POST":
        msgs = []
        if request.POST.get('relatedtreatments') is None:
            msgs.append("Por favor, marca al menos una de las casillas.")
            return render(request, 'tfgcore/question03.html', {"msgs": msgs})
        answers = Answers.objects.filter(user=request.user)[0]
        relatedtreatments = request.POST.getlist('relatedtreatments')
        if '1' in relatedtreatments:
            answers.answer02a = True
        if '2' in relatedtreatments:
            answers.answer02b = True
        if '3' in relatedtreatments:
            answers.answer02c = True
        if '4' in relatedtreatments:
            answers.answer02d = True
        if '5' in relatedtreatments:
            answers.answer02e = True
        if '6' in relatedtreatments:
            answers.answer02f = True
        if '7' in relatedtreatments:
            answers.answer02g = True
        if '8' in relatedtreatments:
            answers.answer02h = True
        if '9' in relatedtreatments:
            answers.answer02i = True
        if '10' in relatedtreatments:
            answers.answer02j = True
        if '11' in relatedtreatments:
            answers.answer02k = True
        answers.save()
        return redirect(reverse('tfgcore:question04'))
    return render(request, 'tfgcore/question03.html')


@login_required
def question04(request):
    if request.method == "POST":
        answers = Answers.objects.filter(user=request.user)[0]
        answers.answer03a = int(request.POST.get('answer03a'))
        answers.answer03b = int(request.POST.get('answer03b'))
        answers.answer03c = int(request.POST.get('answer03c'))
        answers.answer03d = int(request.POST.get('answer03d'))
        answers.answer03e = int(request.POST.get('answer03e'))
        answers.answer03f = int(request.POST.get('answer03f'))
        answers.answer03g = int(request.POST.get('answer03g'))
        answers.answer03other = (request.POST.get('otherreasons'))
        answers.save()
        return redirect(reverse('tfgcore:question05'))
    return render(request, 'tfgcore/question04.html')


@login_required
def question05(request):
    if request.method == "POST":
        msgs = []
        if request.POST.get('healthprofession') is None:
            msgs.append("No has marcado ninguna de las opciones.")
            return render(request, 'tfgcore/question05.html', {'msgs': msgs})
        answers = Answers.objects.filter(user=request.user)[0]
        healthprofession = request.POST.getlist('healthprofession')
        if '1' in healthprofession:
            answers.answer04a = True
        if '2' in healthprofession:
            answers.answer04b = True
        if '3' in healthprofession:
            answers.answer04c = True
        if '4' in healthprofession:
            answers.answer04d = True
        if '5' in healthprofession:
            answers.answer04e = True
        if '6' in healthprofession:
            answers.answer04f = True
        if '7' in healthprofession:
            answers.answer04g = True
        if '8' in healthprofession:
            answers.answer04h = True
        answers.save()
        return redirect(reverse('tfgcore:question06'))
    return render(request, 'tfgcore/question05.html')


@login_required
def question06(request):
    if request.method == "POST":
        if 'knowntreatments' in request.POST:
            knowntreatments = request.POST.getlist('treatment')
            if len(knowntreatments) == 0:
                # user doesn't know any treatments so he cannot review any treatments -> we send him to the next view in the questionnaire.
                return redirect(reverse('tfgcore:question07'))
            else:
                print(knowntreatments)
                return render(request, 'tfgcore/question06b.html', {'knowntreatments': knowntreatments})
        else:
            print(request.POST)
            answers = Answers.objects.filter(user=request.user)[0]
            answers.answer05a = int(request.POST.get('answer05a', -1))
            answers.answer05b = int(request.POST.get('answer05b', -1))
            answers.answer05c = int(request.POST.get('answer05c', -1))
            answers.answer05d = int(request.POST.get('answer05d', -1))
            answers.answer05e = int(request.POST.get('answer05e', -1))
            answers.answer05f = int(request.POST.get('answer05f', -1))
            answers.answer05g = int(request.POST.get('answer05g', -1))
            answers.answer05h = int(request.POST.get('answer05h', -1))
            answers.answer05i = int(request.POST.get('answer05i', -1))

tfgcore/templates/tfgcore/aviso_legal.html
{% extends "base.html" %}
{% load static %}
{% block body %}
<section class="section">
    <div class="content">
        <h1 class="title is-1">Aviso Legal</h1>
        <p>
            Este dominio y todos sus contenidos visualizables son propiedad de Markus Barth Classen. 
            Contacto por correo electrónico: <a href="mailto:tfg@markusbarth.net">tfg@markusbarth.net</a>
            Se prohibe la reproducción de los contenidos sin autorización previa del autor, salvo aquellas
            partes publicadas bajo licencias libres como Creative Commons.
        </p>
        <p>
            La finalidad de este sitio web es la recopilación de datos mediante encuesta. Estos datos se
            usarán para la investigación científica. Es posible que los datos se usen para fines educativos
            en la Universidad Miguel Hernández. Código OIR TFG.GFI.EBV.MWBC.250209.
        </p>
        <p>
            Los datos recopilados en la encuesta se guardarán en una base de datos. 
            No se guardarán datos identificativos. La comprobación de identidad de los datos para poder
            facilitar el ejercicio de los derechos ARCO de los participantes de la encuesta se realizará
            mediante comparación de hashes.
        </p>
        <p>
            Todos los participantes pueden ejercer sus derechos de acceso, rectificación, cancelación y oposición 
            de su datos personales, aunque no se hayan guardado datos identificativos. Para este fin pueden 
            notificar su intención a través del correo electrónico <a href="mailto:tfg@markusbarth.net">tfg@markusbarth.net</a>.
        </p>
        
        <p>
            Este sitio web utiliza cookies como mecanismo de seguridad (para evitar ataques XSRF) y la gestión de sesiones
            de cada encuesta. El uso de cookies se limita a lo estrictamente necesario para estas finalidades.
        </p>
    </div>
</section>
{% endblock %}

tfgcore/templates/tfgcore/bye.html
{% extends "baseform.html" %}
{% load static %}
{% block progress %}
<figure class="image px-5">
    <img src="{% static 'tfgcore/img/bye.svg' %}">
</figure>
{% endblock %}

{% block body %}
<section class="section">
    <h2 class="is-size-5">¡Muchas Gracias por tu tiempo!</h2>
    <form method="post" id="questionnaire">
        <div class="control my-4">
            Agradezco mucho que has participado en esta encuesta.
            Si tienes dudas o preguntas relacionadas con la fisioterapia
            no dudes en escribirme al <a href="mailto:tfg@markusbarth.net">tfg@markusbarth.net</a>.
        </div>
    </form>
</section>
{% endblock %}

tfgcore/templates/tfgcore/landing.html
{% extends "base.html" %}
{% load static %}

{% block body %}
<section class="hero is-link">
    <div class="hero-body">
        <div class="">
            
        </div>
        <div class="section">
            <h1 class="title">¡Hola!</h1>
            <h2 class="subtitle">Tengo algunas preguntas para tí.</h2>
        </div>
        <div class="section">
            <div class="columns">
                <div class="column is-3">
                    <img src="{% static 'tfgcore/img/avatar.svg' %}" >
                </div>
                <div class="column is-6">
                    <p>
                        Me llamo Markus y estoy haciendo un trabajo
                        sobre la imagen que tienen las personas como tú
                        de la fisioterapia.
                    </p>
                    <p>
                        Para ello me gustaría saber lo que tú piensas
                        y lo que sabes de la fisioterapia. 
                    </p>
                    <p>
                        A cambio te contaré algunas cosillas sobre este
                        fascinante trabajo. 
                    </p>
                    <p>
                        Qué me dices, ¿te animas?
                    </p>
                    <div class="section">
                        <a href="{% url 'tfgcore:personaldata' %}" class="button is-success">Adelante!</a>
                        <a href="https://google.com" class="button is-danger">No gracias.</a>
                    </div>
                    <p>
                        Solicito su participación en el trabajo de investigación titulado La imagen de la fisioterapia en la población de Guardamar del Segura y
                        entorno, cuyo responsable (tutor/a) es Eduardo Bueno Vergara consiste en investigar los conocimientos que tienen las personas que viven en 
                        Guardamar del Segura y sus alrededores sobre la fisioterapia, así como posibles sesgos en estos conocimientos.
                        Se podrá cumplimentar desde 01/04/2025 hasta 15/04/2025. La participación es totalmente voluntaria 
                        (si no desea participar o si se retira anticipadamente no habrá ninguna consecuencia) 
                        y anónima (no se dispondrá de ningún dato que le identifique). 
                        Si tiene alguna pregunta puede consultar en este correo: 
                        <a href="mailto:tfg@markusbarth.net">tfg@markusbarth.net</a>. 
                        Si usted responde se entiende de forma tácita que ha comprendido en que consiste este estudio, 
                        que ha podido preguntar y aclarar las dudas que se le hubieran planteado y que acepta participar. 
                        El equipo investigador le agradece su valioso tiempo.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

tfgcore/templates/tfgcore/personaldata.html
{% extends "baseform.html" %}
{% load static %}
{% block progress %}
<figure class="image px-5">
    <img src="{% static 'tfgcore/img/progress_personal_data.svg' %}">
</figure>
{% endblock %}
{% block body %}
<section class="section">
    {% if msgs %}
        <div class="message is-danger">
            <div class="message-header">
                <p>Echa un vistazo</p>
            </div>
            <div class="message-body">
                <div class="content">
                    {% for msg in msgs %}
                        <p>
                            {{msg}}
                        </p>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% else %}
            <div class="content">
                <p>
                    Tus datos se guardarán de forma anonimizada, es decir, que no habrá manera de saber  qué persona 
                    ha dado estas respuestas. Sólo se guardará una huella (un hash) de tu correo electrónico, 
                    pero no el correo electrónico. El motivo de hacer esto es poder asegurar que una persona 
                    no rellena dos veces la encuesta.
                </p> 
                <p>
                    Te preguntaré también sobre algunas enfermedades que has tenido o hábitos, como fumar o si haces deporte 
                    y te pediré tu edad. Estos datos me sirven para estudiar la relación que puede haber entre
                    estas características y la imagen que tienes de la fisioterapia, así como de la información de la que dispones
                    sobre ella.
                </p>
            </div>
        {% endif %}
    <div>
        <form method="post" id="questionnaire">
            {% csrf_token %}
            <div class="box has-background-warning"> 
                <div class="field is-horizontal">
                    <div class="field-label is-normal">
                        <label class="label">Edad</label>
                    </div>
                    <div class="field-body">
                        <div class="field">
                            <p class="control is-expanded">
                                <div class="select is-primary">
                                    <select  name="agerange">
                                        <option value="0" {% if formdata.agerange == "0" %}selected{% endif %}>Selecciona una opción</option>
                                        <option value="1" {% if formdata.agerange == "1" %}selected{% endif %}>18-24 años</option>
                                        <option value="2" {% if formdata.agerange == "2" %}selected{% endif %}>25-34 años</option>
                                        <option value="3" {% if formdata.agerange == "3" %}selected{% endif %}>35-44 años</option>
                                        <option value="4" {% if formdata.agerange == "4" %}selected{% endif %}>45-54 años</option>
                                        <option value="5" {% if formdata.agerange == "5" %}selected{% endif %}>55-64 años</option>
                                        <option value="6" {% if formdata.agerange == "6" %}selected{% endif %}>65 o más años</option>
                                    </select>
                                </div>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="field is-horizontal">
                    <div class="field-label is-normal">
                        <label class="label">Género</label>
                    </div>
                    <div class="field-body">
                        <div class="field">
                            <p class="control is-expanded">
                                <div class="select is-primary">
                                    <select  name="gender">
                                        <option value="">Selecciona una opción</option>
                                        <option value="MALE" {% if formdata.gender == "MALE" %}selected{% endif %}>Hombre</option>
                                        <option value="FEMALE" {% if formdata.gender == "FEMALE" %}selected{% endif %}>Mujer</option>
                                        <option value="TRANSGENDER" {% if formdata.gender == "TRANSGENDER" %}selected{% endif %}>Transgénero</option>
                                        <option value="AGENDER" {% if formdata.gender == "AGENDER" %}selected{% endif %}>Asexual</option>
                                        <option value="GENDERFLUID" {% if formdata.gender == "GENDERFLUID" %}selected{% endif %}>Género fluido</option>
                                        <option value="NONBINARY" {% if formdata.gender == "NONBINARY" %}selected{% endif %}>No binary</option>
                                        <option value="GENDERQUEER" {% if formdata.gender == "GENDERQUEER" %}selected{% endif %}>Queer</option>
                                        <option value="NA" {% if formdata.gender == "NA" %}selected{% endif %}>No quiero especificar</option>
                                    </select>
                                </div>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="field is-horizontal">
                    <div class="field-label is-normal">
                        <label class="label">Estudios</label>
                    </div>
                    <div class="field-body">
                        <div class="field">
                            <p class="control is-expanded">
                                <div class="select is-primary">
                                    <select  name="education">
                                        <option value="">Selecciona una opción</option>
                                        <option value="1" {% if formdata.gender == "1" %}selected{% endif %}>Educación secundaria obligatoria (EGB/ESO)</option>
                                        <option value="2" {% if formdata.gender == "2" %}selected{% endif %}>Bachillerato</option>
                                        <option value="3" {% if formdata.gender == "3" %}selected{% endif %}>FP grado medio</option>
                                        <option value="4" {% if formdata.gender == "4" %}selected{% endif %}>FP grado superior</option>
                                        <option value="5" {% if formdata.gender == "5" %}selected{% endif %}>Estudios universitarios</option>
                                        <option value="6" {% if formdata.gender == "6" %}selected{% endif %}>Estudios de posgrado</option>
                                        <option value="0" {% if formdata.gender == "0" %}selected{% endif %}>No quiero especificar</option>
                                    </select>
                                </div>
                            </p>
                        </div>
                    </div>
                </div>
                <!--
                <div class="field is-horizontal">
                    <div class="field-label is-normal">
                        <label class="label">Código Postal</label>
                    </div>
                    <div class="field-body">
                        <div class="field">
                            <p class="control is-expanded has-icons-left">
                                <input class="input" type="text" placeholder="Código Postal" name="postcode">
                                <span class="icon is-small is-left">
                                    <i class="fas fa-map-marker-alt"></i>
                                </span>
                            </p>
                        </div>
                    </div>
                </div>
                -->
                <div class="field is-horizontal">
                    <div class="field-label is-normal">
                        <label class="label">Correo electrónico</label>
                    </div>
                    <div class="field-body">
                        <div class="field">
                            <p class="control is-expanded has-icons-left">
                                <input class="input" type="text" placeholder="Correo electrónico" name="email" value="{{formdata.email}}">
                                <span class="icon is-small is-left">
                                    <i class="fas fa-envelope"></i>
                                </span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box has-background-warning">
                <div class="field">
                    <label class="label">¿Fumas?</label>
                    <div class="control">
                        <input class="is-checkradio" id="smokerNo" type="radio" name="smoker" value="No" checked="checked">
                        <label for="smokerNo">No</label>
                        <input class="is-checkradio" id="smokerYes" type="radio" name="smoker" value="Yes">
                        <label for="smokerYes">Sí</label>
                    </div>
                </div>
                <div class="field">
                    <label class="label">¿Haces deporte?</label>
                    <div class="control">
                        <input class="is-checkradio" id="sportNo" type="radio" name="sport" value="No" checked="checked">
                        <label for="sportNo">No</label>
                        <input class="is-checkradio" id="sportYes" type="radio" name="sport" value="Yes">
                        <label for="sportYes">Sí</label>
                    </div>
                </div>
            </div>
            <div class="box has-background-warning">
                <div class="field">
                    <label class="label">¿Eres profesional sanitario?</label>
                    <div class="control">
                        <input class="is-checkradio" id="healthprofessionalNo" type="radio" name="healthprofessional" value="No" checked="checked" onchange="toggleProfessionPanel(event)">
                        <label for="healthprofessionalNo">No</label>
                        <input class="is-checkradio" id="healthprofessionalYes" type="radio" name="healthprofessional" value="Yes"  onchange="toggleProfessionPanel(event)">
                        <label for="healthprofessionalYes">Sí</label>
                    </div>
                </div>
                <div class="field">
                    <label class="label">¿Tienes una enfermedad autoimune o neurodegenerativa?</label>
                    <div class="control">
                        <input class="is-checkradio" id="pathologies01" type="radio" name="pathologies" value="No" checked="checked" onchange="togglePathologies(event)">
                        <label for="pathologies01">No</label>
                        <input class="is-checkradio" id="pathologies02" type="radio" name="pathologies" value="Yes" onchange="togglePathologies(event)">
                        <label for="pathologies02">Sí</label>
                    </div>
                </div>
            </div>
        </form>
        <div class="level my-5">
            <div class="level-left">
                <button class="button is-info" onclick="showModal()">Vamos a seguir!</button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block modalcontent %}
    <div class="content">
        <p>
            En España para ser fisioterapeuta hay que cursar
            una carrera universitaria de cuatro años.
        </p>
        <p>
            Todos los fisioterapeutas tienen obligación de
            colegiarse. Puedes consultar un listado de todos
            los fisioterapeutas en la Comunidad Valenciana
            en la <a href="https://www.colfisiocv.com/node/26074" target="_blank">
                página del Colegio de Fisioterapeutas</a>
            y así puedes ver si tu fisio está colegiado.
        </p>
    <button class="button" form="questionnaire">Cerrar y seguir</button>
    </div>
{% endblock %}

tfgcore/templates/tfgcore/question01.html
{% extends "baseform.html" %}
{% load static %}
{% block progress %}
<figure class="image px-5">
    <img src="{% static 'tfgcore/img/progress_question01.svg' %}">
</figure>
{% endblock %}

{% block body %}
<section class="section">
    {% if msgs %}
        <div class="message is-danger">
            <div class="message-header">
                <p>Echa un vistazo</p>
            </div>
            <div class="message-body">
                <div class="content">
                    {% for msg in msgs %}
                        <p>
                            {{msg}}
                        </p>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}
    <h2  class="is-size-5">¿Has estado en tratamiento de fisioterapia en los últimos años?</h2>
    <form method="post" id="questionnaire">
        {% csrf_token %}
        <div class="control my-4">
            <div class="field">
                <label class="radio label" for="1">
                    <input id="1" value="1" type="radio" name="intreatment">
                    No
                </label>
            </div>
            <div class="field">
                <label class="radio label" for="2">
                    <input id="2" value="2" type="radio" name="intreatment">
                    Sí, hace menos de un año.
                </label>
            </div>
            <div class="field">
                <label class="label radio" for="3">
                    <input id="3" value="3" type="radio" name="intreatment">
                    Sí, hace más de un año pero menos de tres años.
                </label>
            </div>
            <div class="field">
                <label class="label radio" for="4">
                    <input id="4" value="4" type="radio" name="intreatment">
                    Sí, hace más de tres años.
                </label>
            </div>
        </div>
    </form>
    <div class="level my-5">
        <div class="level-left">
            <button class="button is-info" onclick="showModal()">Vamos a seguir!</button>
        </div>
    </div>
</section>
{% endblock %}

{% block modalcontent %}
    <div class="content">
        <p>
        La gran mayoría de las lumbalgias son inespecíficas, es decir, que no 
        se puede determinar la causa. Así que, no pienses directamente en una 
        hernia si tienes dolor de espalda baja. Y aunque fuera una hernia, que
        sepas que la gran mayoría de ellas se resuelven solas y el tratamiento 
        conservador suele dar buenos resultados.
        </p>
    <button class="button" form="questionnaire">Cerrar y seguir</button>
    </div>
{% endblock %}